# Changes here will be overwritten by Copier
_commit: v0.0.1
_src_path: gh:ninanor/python-template
author_name: Niccolò Cantù
debug: false
default_branch_name: main
docker: false
email: niccolo.cantu@nina.no
project_name: Radar data scripts
project_slug: radar_data
repo_name: radar_data_scripts
repo_org: ninanor
template_type: python
type_annotations: true
