

output_dir ?= ./output
radar_name ?= max_rental
location_name ?= lutelandet
month ?= 1
year ?= 2024

table_name ?= radar

location_dir := $(output_dir)/$(table_name)/radar_name=$(radar_name)/location=$(location_name)/
yearly_path := $(location_dir)year=$(year)/
monthly_path := $(yearly_path)month=$(month)/


.PHONY: error yearly monthly location

error:
    @echo "Please choose one of the following target: location, yearly, monthly"


$(location_dir) $(yearly_path) $(monthly_path):
	@echo "create $@ directory"
	mkdir -p $@


yearly: $(yearly_path)
	pg_restore -f - $(input) -t $(table_name) | pg_dedump -o $(yearly_path) -d y$(table_name)$(year)$(month).ddb
	rm y$(table_name)$(year)$(month).ddb


monthly: $(monthly_path)
	pg_restore -f - $(input) -t $(table_name) | pg_dedump -o $(monthly_path) -d m$(table_name)$(year)$(month).ddb
	rm m$(table_name)$(year)$(month).ddb


location: $(location_dir)
	pg_restore -f - $(input) -t $(table_name) | pg_dedump -o $(location_dir) -d l$(table_name)$(year)$(month).ddb
	rm l$(table_name)$(year)$(month).ddb
